In [1]:
import pandas as pd
import numpy as np

In [2]:
df_pdsi = pd.read_csv("processed/wildfire_augmented_pdsi.csv")
df_pr = pd.read_csv("processed/wildfire_augmented_pr.csv")
df_rmax = pd.read_csv("processed/wildfire_augmented_rmax.csv")
df_rmin = pd.read_csv("processed/wildfire_augmented_rmin.csv")
df_tmmn = pd.read_csv("processed/wildfire_augmented_tmmn.csv")
df_tmmx = pd.read_csv("processed/wildfire_augmented_tmmx.csv")
df_vs = pd.read_csv("processed/wildfire_augmented_vs.csv")
df_sph = pd.read_csv("processed/wildfire_augmented_sph.csv")

C:\Users\jepoisso\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (17,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df = pd.merge(df_pdsi, df_pr)
df = pd.merge(df, df_rmax)
df = pd.merge(df, df_rmin)
df = pd.merge(df, df_rmax)
df = pd.merge(df, df_tmmn)
df = pd.merge(df, df_tmmx)
df = pd.merge(df, df_vs)
df = pd.merge(df, df_sph)
df

,Unnamed: 0,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,...,vs_min,vs_max,vs_avg,vs_count,vs_first,sph_min,sph_max,sph_avg,sph_count,sph_first
0,0,1,1,2005,2453403.5,33,1300.0,9.0,Miscellaneous,2453403.5,...,61.0,61.0,61.0,2.0,61.0,311.0,311.0,311.0,2.0,311.0
1,1,2,2,2004,2453137.5,133,845.0,1.0,Lightning,2453137.5,...,25.0,25.0,25.0,2.0,25.0,363.0,363.0,363.0,2.0,363.0
2,2,3,3,2004,2453156.5,152,1921.0,5.0,Debris Burning,2453156.5,...,21.0,21.0,21.0,2.0,21.0,657.0,657.0,657.0,2.0,657.0
3,3,4,4,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,...,17.0,17.0,17.0,2.0,17.0,463.0,463.0,463.0,2.0,463.0
4,4,5,5,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,...,17.0,17.0,17.0,2.0,17.0,463.0,463.0,463.0,2.0,463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880460,1880461,300348363,2015,2457291.5,269,1726.0,13.0,Missing/Undefined,2457291.5,...,19.0,19.0,19.0,2.0,19.0,751.0,751.0,751.0,2.0,751.0
1880461,1880461,1880462,300348373,2015,2457300.5,278,126.0,9.0,Miscellaneous,NaN,...,28.0,28.0,28.0,2.0,28.0,782.0,782.0,782.0,2.0,782.0
1880462,1880462,1880463,300348375,2015,2457144.5,122,2052.0,13.0,Missing/Undefined,NaN,...,25.0,25.0,25.0,2.0,25.0,621.0,621.0,621.0,2.0,621.0
1880463,1880463,1880464,300348377,2015,2457309.5,287,2309.0,13.0,Missing/Undefined,NaN,...,31.0,31.0,31.0,2.0,31.0,739.0,739.0,739.0,2.0,739.0
1880464,1880464,1880465,300348399,2015,2457095.5,73,2128.0,9.0,Miscellaneous,NaN,...,18.0,18.0,18.0,2.0,18.0,349.0,349.0,349.0,2.0,349.0

In [4]:
df.to_csv("wildfires_complete.csv")
df.describe()

,Unnamed: 0,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,CONT_DATE,CONT_DOY,...,vs_min,vs_max,vs_avg,vs_count,vs_first,sph_min,sph_max,sph_avg,sph_count,sph_first
count,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,997827.000000,1.880465e+06,9.889340e+05,988934.000000,...,1.880465e+06,1.880465e+06,1.880465e+06,1880465.0,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,1880465.0,1.880465e+06
mean,9.402320e+05,9.402330e+05,5.484020e+07,2.003710e+03,2.453064e+06,1.647191e+02,1453.014326,5.979037e+00,2.453238e+06,172.656766,...,8.240559e+02,8.240559e+02,8.240559e+02,2.0,8.240559e+02,1.493395e+03,1.493395e+03,1.493395e+03,2.0,1.493395e+03
std,5.428436e+05,5.428436e+05,1.011963e+08,6.663099e+00,2.434573e+03,9.003891e+01,405.960963,3.483860e+00,2.687548e+03,84.320348,...,5.007650e+03,5.007650e+03,5.007650e+03,0.0,5.007650e+03,4.917570e+03,4.917570e+03,4.917570e+03,0.0,4.917570e+03
min,0.000000e+00,1.000000e+00,1.000000e+00,1.992000e+03,2.448622e+06,1.000000e+00,0.000000,1.000000e+00,2.448622e+06,1.000000,...,4.000000e+00,4.000000e+00,4.000000e+00,2.0,4.000000e+00,3.200000e+01,3.200000e+01,3.200000e+01,2.0,3.200000e+01
25%,4.701160e+05,4.701170e+05,5.055000e+05,1.998000e+03,2.451084e+06,8.900000e+01,1240.000000,3.000000e+00,2.450701e+06,102.000000,...,2.800000e+01,2.800000e+01,2.800000e+01,2.0,2.800000e+01,4.340000e+02,4.340000e+02,4.340000e+02,2.0,4.340000e+02
50%,9.402320e+05,9.402330e+05,1.067761e+06,2.004000e+03,2.453178e+06,1.640000e+02,1457.000000,5.000000e+00,2.453466e+06,181.000000,...,3.700000e+01,3.700000e+01,3.700000e+01,2.0,3.700000e+01,6.660000e+02,6.660000e+02,6.660000e+02,2.0,6.660000e+02
75%,1.410348e+06,1.410349e+06,1.910639e+07,2.009000e+03,2.455036e+06,2.300000e+02,1708.000000,9.000000e+00,2.455754e+06,232.000000,...,4.900000e+01,4.900000e+01,4.900000e+01,2.0,4.900000e+01,9.570000e+02,9.570000e+02,9.570000e+02,2.0,9.570000e+02
max,1.880464e+06,1.880465e+06,3.003484e+08,2.015000e+03,2.457388e+06,3.660000e+02,2359.000000,1.300000e+01,2.457392e+06,366.000000,...,3.276700e+04,3.276700e+04,3.276700e+04,2.0,3.276700e+04,3.276700e+04,3.276700e+04,3.276700e+04,2.0,3.276700e+04