In [64]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [65]:
orig_df = pd.read_csv("wildfires.csv")
orig_df

C:\Users\jepoisso\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (16,18) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,1,1,2005,2453403.5,33,1300.0,9.0,Miscellaneous,2453403.5,33.0,1730.0,0.10,A,40.036944,-121.005833,CA,63,63.0,Plumas
1,2,2,2004,2453137.5,133,845.0,1.0,Lightning,2453137.5,133.0,1530.0,0.25,A,38.933056,-120.404444,CA,61,61.0,Placer
2,3,3,2004,2453156.5,152,1921.0,5.0,Debris Burning,2453156.5,152.0,2024.0,0.10,A,38.984167,-120.735556,CA,17,17.0,El Dorado
3,4,4,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1400.0,0.10,A,38.559167,-119.913333,CA,3,3.0,Alpine
4,5,5,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1200.0,0.10,A,38.559167,-119.933056,CA,3,3.0,Alpine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880461,300348363,2015,2457291.5,269,1726.0,13.0,Missing/Undefined,2457291.5,269.0,1843.0,0.01,A,40.481637,-122.389375,CA,NaN,NaN,NaN
1880461,1880462,300348373,2015,2457300.5,278,126.0,9.0,Miscellaneous,NaN,NaN,NaN,0.20,A,37.617619,-120.938570,CA,NaN,NaN,NaN
1880462,1880463,300348375,2015,2457144.5,122,2052.0,13.0,Missing/Undefined,NaN,NaN,NaN,0.10,A,37.617619,-120.938570,CA,NaN,NaN,NaN
1880463,1880464,300348377,2015,2457309.5,287,2309.0,13.0,Missing/Undefined,NaN,NaN,NaN,2.00,B,37.672235,-120.898356,CA,NaN,NaN,NaN
1880464,1880465,300348399,2015,2457095.5,73,2128.0,9.0,Miscellaneous,NaN,NaN,NaN,0.10,A,34.263217,-116.830950,CA,NaN,NaN,NaN

In [66]:
merge_datasets = [{
    'filename': 'rmax_by_FOD_ordered.csv',
    'src_col_name': 'PDSI',
    'tar_col_name': 'RMAX'
},
{
    'filename': 'rmin_by_FOD_ordered.csv',
    'src_col_name': 'PDSI',
    'tar_col_name': 'RMIN'
},
{
    'filename': 'tmmn_by_FOD_ordered.csv',
    'src_col_name': 'max_temp',
    'tar_col_name': 'TMMN'
},
{
    'filename': 'tmmx_by_FOD_ordered.csv',
    'src_col_name': 'max_temp',
    'tar_col_name': 'TMMX'
},
{
    'filename': 'vs_by_FOD_ordered.csv',
    'src_col_name': 'PDSI',
    'tar_col_name': 'VS'
}]

In [67]:
for _, dataset in enumerate(merge_datasets):
    ds_df = pd.read_csv(dataset['filename'])
    print("opened %s" % (dataset['filename']))
    ds_df = ds_df.rename(columns={dataset['src_col_name']: dataset['tar_col_name']})
    orig_df = pd.merge(orig_df, ds_df[['FOD_ID',dataset['tar_col_name']]], left_on='FOD_ID', right_on='FOD_ID')
    print("merged %s" % (dataset['filename']))

opened rmax_by_FOD_ordered.csv
merged rmax_by_FOD_ordered.csv
opened rmin_by_FOD_ordered.csv
merged rmin_by_FOD_ordered.csv
opened tmmn_by_FOD_ordered.csv
merged tmmn_by_FOD_ordered.csv
opened tmmx_by_FOD_ordered.csv
merged tmmx_by_FOD_ordered.csv
opened vs_by_FOD_ordered.csv
merged vs_by_FOD_ordered.csv

In [68]:
orig_df

,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,FIPS_CODE,FIPS_NAME,RMAX,RMIN,TMMN,TMMX,VS
0,1,1,2005,2453403.5,33,1300.0,9.0,Miscellaneous,2453403.5,33.0,1730.0,0.10,A,40.036944,-121.005833,CA,63,63.0,Plumas,70.6,44.3,271.3,280.9,6.9
1,2,2,2004,2453137.5,133,845.0,1.0,Lightning,2453137.5,133.0,1530.0,0.25,A,38.933056,-120.404444,CA,61,61.0,Placer,66.7,34.0,273.4,289.1,3.2
2,3,3,2004,2453156.5,152,1921.0,5.0,Debris Burning,2453156.5,152.0,2024.0,0.10,A,38.984167,-120.735556,CA,17,17.0,El Dorado,40.7,27.3,286.3,301.0,1.8
3,4,4,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1400.0,0.10,A,38.559167,-119.913333,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2
4,5,5,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1200.0,0.10,A,38.559167,-119.933056,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880461,300348363,2015,2457291.5,269,1726.0,13.0,Missing/Undefined,2457291.5,269.0,1843.0,0.01,A,40.481637,-122.389375,CA,NaN,NaN,NaN,57.6,15.8,288.9,307.2,2.4
1880461,1880462,300348373,2015,2457300.5,278,126.0,9.0,Miscellaneous,NaN,NaN,NaN,0.20,A,37.617619,-120.938570,CA,NaN,NaN,NaN,72.1,26.7,286.8,299.8,1.3
1880462,1880463,300348375,2015,2457144.5,122,2052.0,13.0,Missing/Undefined,NaN,NaN,NaN,0.10,A,37.617619,-120.938570,CA,NaN,NaN,NaN,69.1,17.9,286.9,306.0,3.0
1880463,1880464,300348377,2015,2457309.5,287,2309.0,13.0,Missing/Undefined,NaN,NaN,NaN,2.00,B,37.672235,-120.898356,CA,NaN,NaN,NaN,60.8,19.3,290.9,305.4,3.6
1880464,1880465,300348399,2015,2457095.5,73,2128.0,9.0,Miscellaneous,NaN,NaN,NaN,0.10,A,34.263217,-116.830950,CA,NaN,NaN,NaN,70.8,16.3,272.7,289.9,2.5

In [69]:
pd.set_option('display.max_columns', None)
pdsi_data = pd.read_csv("processed/wildfire_augmented_pdsi.csv")
pdsi_data = pdsi_data.rename(columns={'pdsi_first': 'PDSI'})
orig_df = pd.merge(orig_df, pdsi_data[['FOD_ID','PDSI']], left_on='FOD_ID', right_on='FOD_ID')
orig_df

C:\Users\jepoisso\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (17,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,FIPS_CODE,FIPS_NAME,RMAX,RMIN,TMMN,TMMX,VS,PDSI
0,1,1,2005,2453403.5,33,1300.0,9.0,Miscellaneous,2453403.5,33.0,1730.0,0.10,A,40.036944,-121.005833,CA,63,63.0,Plumas,70.6,44.3,271.3,280.9,6.9,-0.661443
1,2,2,2004,2453137.5,133,845.0,1.0,Lightning,2453137.5,133.0,1530.0,0.25,A,38.933056,-120.404444,CA,61,61.0,Placer,66.7,34.0,273.4,289.1,3.2,-2.116477
2,3,3,2004,2453156.5,152,1921.0,5.0,Debris Burning,2453156.5,152.0,2024.0,0.10,A,38.984167,-120.735556,CA,17,17.0,El Dorado,40.7,27.3,286.3,301.0,1.8,-2.589112
3,4,4,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1400.0,0.10,A,38.559167,-119.913333,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2,-2.705879
4,5,5,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1200.0,0.10,A,38.559167,-119.933056,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2,-2.705879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880461,300348363,2015,2457291.5,269,1726.0,13.0,Missing/Undefined,2457291.5,269.0,1843.0,0.01,A,40.481637,-122.389375,CA,NaN,NaN,NaN,57.6,15.8,288.9,307.2,2.4,-3.370119
1880461,1880462,300348373,2015,2457300.5,278,126.0,9.0,Miscellaneous,NaN,NaN,NaN,0.20,A,37.617619,-120.938570,CA,NaN,NaN,NaN,72.1,26.7,286.8,299.8,1.3,-2.658307
1880462,1880463,300348375,2015,2457144.5,122,2052.0,13.0,Missing/Undefined,NaN,NaN,NaN,0.10,A,37.617619,-120.938570,CA,NaN,NaN,NaN,69.1,17.9,286.9,306.0,3.0,-3.084456
1880463,1880464,300348377,2015,2457309.5,287,2309.0,13.0,Missing/Undefined,NaN,NaN,NaN,2.00,B,37.672235,-120.898356,CA,NaN,NaN,NaN,60.8,19.3,290.9,305.4,3.6,-2.687376
1880464,1880465,300348399,2015,2457095.5,73,2128.0,9.0,Miscellaneous,NaN,NaN,NaN,0.10,A,34.263217,-116.830950,CA,NaN,NaN,NaN,70.8,16.3,272.7,289.9,2.5,-2.271709

In [70]:
def compute_date(row, col_name):
    f_year, doy = row['FIRE_YEAR'], row[col_name]
    if np.isnan(doy):
        return np.nan
    cdate = datetime(f_year, 1, 1) + timedelta(days=np.float64(doy))
    return cdate
    
    
orig_df['DISCOVERY_CDATE'] = orig_df.apply(lambda row: compute_date(row, 'DISCOVERY_DOY'), axis=1)
orig_df['CONT_CDATE'] = orig_df.apply(lambda row: compute_date(row, 'CONT_DOY'), axis=1)

In [71]:
pd.set_option('display.max_columns', None)
orig_df

,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,FIPS_CODE,FIPS_NAME,RMAX,RMIN,TMMN,TMMX,VS,PDSI,DISCOVERY_CDATE,CONT_CDATE
0,1,1,2005,2453403.5,33,1300.0,9.0,Miscellaneous,2453403.5,33.0,1730.0,0.10,A,40.036944,-121.005833,CA,63,63.0,Plumas,70.6,44.3,271.3,280.9,6.9,-0.661443,2005-02-03,2005-02-03
1,2,2,2004,2453137.5,133,845.0,1.0,Lightning,2453137.5,133.0,1530.0,0.25,A,38.933056,-120.404444,CA,61,61.0,Placer,66.7,34.0,273.4,289.1,3.2,-2.116477,2004-05-13,2004-05-13
2,3,3,2004,2453156.5,152,1921.0,5.0,Debris Burning,2453156.5,152.0,2024.0,0.10,A,38.984167,-120.735556,CA,17,17.0,El Dorado,40.7,27.3,286.3,301.0,1.8,-2.589112,2004-06-01,2004-06-01
3,4,4,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1400.0,0.10,A,38.559167,-119.913333,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2,-2.705879,2004-06-29,2004-07-04
4,5,5,2004,2453184.5,180,1600.0,1.0,Lightning,2453189.5,185.0,1200.0,0.10,A,38.559167,-119.933056,CA,3,3.0,Alpine,47.3,17.8,281.1,294.4,2.2,-2.705879,2004-06-29,2004-07-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880460,1880461,300348363,2015,2457291.5,269,1726.0,13.0,Missing/Undefined,2457291.5,269.0,1843.0,0.01,A,40.481637,-122.389375,CA,NaN,NaN,NaN,57.6,15.8,288.9,307.2,2.4,-3.370119,2015-09-27,2015-09-27
1880461,1880462,300348373,2015,2457300.5,278,126.0,9.0,Miscellaneous,NaN,NaN,NaN,0.20,A,37.617619,-120.938570,CA,NaN,NaN,NaN,72.1,26.7,286.8,299.8,1.3,-2.658307,2015-10-06,NaT
1880462,1880463,300348375,2015,2457144.5,122,2052.0,13.0,Missing/Undefined,NaN,NaN,NaN,0.10,A,37.617619,-120.938570,CA,NaN,NaN,NaN,69.1,17.9,286.9,306.0,3.0,-3.084456,2015-05-03,NaT
1880463,1880464,300348377,2015,2457309.5,287,2309.0,13.0,Missing/Undefined,NaN,NaN,NaN,2.00,B,37.672235,-120.898356,CA,NaN,NaN,NaN,60.8,19.3,290.9,305.4,3.6,-2.687376,2015-10-15,NaT
1880464,1880465,300348399,2015,2457095.5,73,2128.0,9.0,Miscellaneous,NaN,NaN,NaN,0.10,A,34.263217,-116.830950,CA,NaN,NaN,NaN,70.8,16.3,272.7,289.9,2.5,-2.271709,2015-03-15,NaT

In [75]:
orig_df = orig_df.drop(['DISCOVERY_DATE', 'DISCOVERY_DOY', 'DISCOVERY_TIME', 'CONT_DATE', 'CONT_DOY', 'CONT_TIME'], axis=1)
orig_df.columns

KeyError: "['DISCOVERY_DATE' 'DISCOVERY_DOY' 'DISCOVERY_TIME' 'CONT_DATE' 'CONT_DOY'\n 'CONT_TIME'] not found in axis"

In [74]:
orig_df.to_csv("wildfires-cleaned.csv")